[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0.86"
async-trait = "0.1.80"
thiserror = "1.0.61"
mockall = { version = "0.12.1" }
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
