[package]
name = "server"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.86"
axum = "0.7.5"
command_use_case = { path = "../command_use_case" }
query_use_case = { path = "../query_use_case" }
serde = { version = "1.0.202", features = ["derive"] }
thiserror.workspace = true
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
