[package]
name = "firestore_store"
edition = "2021"
publish = false

[dependencies]
async-trait.workspace = true
command_use_case.workspace = true
query_use_case.workspace = true
thiserror.workspace = true
tokio.workspace = true
write_model.workspace = true
