[package]
name = "file_system_store"
edition = "2021"
publish = false

[dependencies]
async-trait.workspace = true
command_use_case.workspace = true
query_use_case.workspace = true
serde_json = "1.0.117"
tokio.workspace = true
write_model.workspace = true
